### ISSUE TITLE
Is this package deployed to Maven Central?

### ISSUE THREAD

**Issue by ChameleonTartu** [MikAoJk/norwegian-organization-number-validator#1]
It looks like something I would like to use but it doesn't seem to be deployed to Maven Central. Are you planning to deploy it there?

**Comment by MikAoJk** [comment]
Currently its only deployed to github packages. I will have a look into deploying it to maven central

**Comment by MikAoJk** [comment]
trying to get the package published  on maven central in this branch: 
https://github.com/MikAoJk/norwegian-organization-number-validator/tree/mavencentral

**Comment by MikAoJk** [comment]
Isee that i need to do some work, in order to get it deployed to maven central, will update this issue when its done

**Comment by ChameleonTartu** [comment]
Hi @MikAoJk. It is maybe tricky to deploy for the first time. I guess you know how to do it, so I can leave here the latest setup I used for deploying to Maven Central for one of my projects. [pom.xml](https://github.com/ChameleonTartu/amazon-mws-feeds-maven/blob/master/pom.xml) and [deploy.yml GitHub workflow](https://github.com/ChameleonTartu/amazon-mws-feeds-maven/blob/master/.github/workflows/deploy.yml).

**Comment by MikAoJk** [comment]
@ChameleonTartu 
Thank you very much for example. I now see that I only need to signing and javadoc to get this to deploy to Maven Central.
Currently wokring in this branch https://github.com/MikAoJk/norwegian-organization-number-validator/tree/mavencentral

**Comment by MikAoJk** [comment]
Currently its only deployed here: https://repo1.maven.org/maven2/io/github/MikAoJk/norwegian-organization-number-validator/
will be deployed to: https://search.maven.org but it can take up to four hours

**Comment by MikAoJk** [comment]
https://search.maven.org/artifact/io.github.MikAoJk/norwegian-organization-number-validator/1.0.0/jar
